const MODEL = '@cf/meta/llama-4-scout-17b-16e-instruct';
const UNITS = {
  Barbarian:[1,1],Archer:[2,1],Giant:[3,5],Goblin:[3,1], 'Wall Breaker':[3,2],Balloon:[4,5],Wizard:[5,4],Healer:[6,14],Dragon:[7,20], 'P.E.K.K.A':[8,25], 'Baby Dragon':[9,10],Miner:[10,6], 'Electro Dragon':[11,30],Yeti:[12,18], 'Dragon Rider':[13,25], 'Electro Titan':[14,32], 'Root Rider':[15,20],Thrower:[17,16], 'Meteor Golem':[17,40],Minion:[7,2], 'Hog Rider':[7,5],Valkyrie:[8,8],Golem:[8,30],Witch:[9,12], 'Lava Hound':[9,30],Bowler:[10,6], 'Ice Golem':[11,15],Headhunter:[12,6], 'Apprentice Warden':[13,20],Druid:[14,16]
};
const SPELLS = {'Lightning Spell':5,'Healing Spell':6,'Rage Spell':7,'Jump Spell':9,'Freeze Spell':9,'Clone Spell':10,'Invisibility Spell':11,'Recall Spell':13,'Poison Spell':8,'Earthquake Spell':8,'Haste Spell':9,'Skeleton Spell':9,'Bat Spell':10,'Overgrowth Spell':12,'Revive Spell':15};
const HEROES = ['Barbarian King','Archer Queen','Minion Prince','Grand Warden','Royal Champion'];
const SIEGES = ['None','Wall Wrecker','Battle Blimp','Stone Slammer','Siege Barracks','Log Launcher','Flame Flinger','Battle Drill'];
const nTH = x => Number(String(x).replace(/\D/g,''));
const point = () => ({type:'object',properties:{x:{type:'number'},y:{type:'number'},label:{type:'string'}},required:['x','y','label']});
function schema(th){
 const names=Object.keys(UNITS).filter(x=>UNITS[x][0]<=th);
 const spells=Object.keys(SPELLS).filter(x=>SPELLS[x]<=th);
 const item=(enumNames)=>({type:'object',properties:{name:{type:'string',enum:enumNames},qty:{type:'integer'},role:{type:'string'}},required:['name','qty','role']});
 return {type:'object',properties:{title:{type:'string'},baseRead:{type:'string'},strategyReason:{type:'string'},army:{type:'array',items:item(names)},spells:{type:'array',items:item(spells.length?spells:['Lightning Spell'])},heroes:{type:'array',items:{type:'string',enum:HEROES}},siege:{type:'string',enum:SIEGES},deployment:{type:'array',items:{type:'string'}},timing:{type:'array',items:{type:'string'}},backup:{type:'array',items:{type:'string'}},practice:{type:'array',items:{type:'string'}},warnings:{type:'array',items:{type:'string'}},map:{type:'object',properties:{entry:point(),funnelA:point(),funnelB:point(),main:point(),core:point(),target:point(),spellZones:{type:'array',items:point()}},required:['entry','funnelA','funnelB','main','core','target','spellZones']}},required:['title','baseRead','strategyReason','army','spells','heroes','siege','deployment','timing','backup','practice','warnings','map']};
}
function parse(r){let x=r?.response??r?.result??r;if(typeof x==='object')return x;if(typeof x!=='string')return null;try{return JSON.parse(x.replace(/^```(?:json)?/i,'').replace(/```$/,'').trim());}catch{return null;}}
function validate(p,th){if(!p||!Array.isArray(p.army)||!p.army.length)return 'Army empty';for(const x of p.army){if(!UNITS[x.name]||UNITS[x.name][0]>th||!Number.isInteger(x.qty)||x.qty<1)return 'Invalid troop '+x.name;}if(!Array.isArray(p.spells))return 'Spells missing';for(const x of p.spells){if(!SPELLS[x.name]||SPELLS[x.name]>th||!Number.isInteger(x.qty)||x.qty<1)return 'Invalid spell '+x.name;}if(!p.map||!p.map.entry||!p.map.target||!Array.isArray(p.deployment)||!p.deployment.length)return 'Map or steps missing';return null;}
const respond=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8'}});
async function ask(env,body,th,fix=''){
 const names=Object.keys(UNITS).filter(x=>UNITS[x][0]<=th);
 const spells=Object.keys(SPELLS).filter(x=>SPELLS[x]<=th);
 const prompt=`You are a Clash of Clans attack planner. Selected Town Hall: TH${th}. Mode: ${body.mode}. Notes: ${String(body.message||'').slice(0,1200)}. Valid troops: ${names.join(', ')}. Valid spells: ${spells.join(', ')}. Analyze attached screenshot if present. Return a NONEMPTY practical army array with exact valid names and quantities; spells, hero names, siege, specific ordered deployment, spell timing, backup and practice. Give map percentage coordinates 0-100 for ENTRY, FUNNEL A, FUNNEL B, MAIN ARMY, CORE, TARGET, spell zones. If screenshot is absent, clearly say coordinates are illustrative. Do not invent unseen defenses, claim guaranteed three stars, or pretend exact housing capacity was checked. If no spells available return []. If base design mode, give design guidance only; do not invent layout copy links. Previous validation error: ${fix||'none'}. Reply as JSON only.`;
 const content=[{type:'text',text:prompt}];
 if(body.image){if(!/^data:image\/(jpeg|png|webp);base64,/.test(body.image))throw Error('Invalid screenshot');content.push({type:'image_url',image_url:{url:body.image}});}
 const result=await env.AI.run(MODEL,{messages:[{role:'system',content:'Return only valid JSON with a nonempty army. Follow the provided schema.'},{role:'user',content}],guided_json:schema(th),max_tokens:3500,temperature:0.1});
 return parse(result);
}
export default {async fetch(req,env){
 const u=new URL(req.url);if(req.method==='POST'&&u.pathname==='/api/ask'){
 try{if(!env.AI)return respond({error:'AI binding missing'},500);const body=await req.json();const th=nTH(body.th);if(th<1||th>18)return respond({error:'Select TH1–TH18'},400);if(body.mode==='war'&&!body.image)return respond({error:'Upload a war screenshot'},400);
 let plan=await ask(env,body,th);let err=validate(plan,th);if(err){plan=await ask(env,body,th,err);err=validate(plan,th);}if(err)return respond({error:'AI response invalid after retry: '+err},422);
 const warnings=Array.isArray(plan.warnings)?plan.warnings:[];warnings.push('Exact troop housing, spell capacity, hero unlocks and current meta have NOT been automatically verified; confirm in-game before attacking.');plan.warnings=warnings;
 return respond({plan});}catch(e){return respond({error:e.message||'AI request failed'},500);}}
 return new Response(PAGE,{headers:{'content-type':'text/html;charset=utf-8'}});
}};
const PAGE = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CoC Battle AI</title><style>
*{box-sizing:border-box}body{margin:0;background:#080d17;color:#f7f8ff;font:15px Arial,sans-serif}.wrap{max-width:820px;margin:auto;padding:15px}.box{background:#121d30;border:1px solid #2a3a55;border-radius:16px;padding:16px;margin:12px 0}h1{margin:4px 0 8px}h3{color:#ffcf32;margin:16px 0 8px}small{color:#aebed5}select,textarea,button{width:100%;padding:12px;background:#202e47;border:1px solid #465773;border-radius:10px;color:white;font-size:15px}textarea{min-height:78px;margin-top:12px}.modes{display:grid;grid-template-columns:1fr 1fr;gap:8px}.active,.go{background:#ffcf32;color:#161616;font-weight:800}.upload{display:block;text-align:center;border:2px dashed #52627d;padding:20px;border-radius:12px;cursor:pointer}#file{display:none}#previewBox{display:none;position:relative;margin-top:12px}#preview{display:block;width:100%;border-radius:12px}#map{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}#result{display:none}.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.unit,.step{padding:11px;background:#0c1525;border-radius:10px;margin:6px 0;overflow-wrap:anywhere}.unit b{color:#ffcf32}.step{border-left:3px solid #ffcf32}.go{margin-top:12px}.warn{color:#ffb77e}#status{padding:8px;color:#a9c7e8}button:disabled{opacity:.5}
</style></head><body><div class="wrap"><div class="box"><small>AI STRATEGY ASSISTANT</small><h1>⚔️ CoC Battle AI</h1><small>Screenshot • Army • Funnel • Roadmap</small></div><div class="box"><h3>1. Town Hall</h3><select id="th"><option value="">Select Town Hall</option>${Array.from({length:18},(_,i)=>`<option value="${i+1}">TH${i+1}</option>`).join('')}</select><h3>2. Mode</h3><div class="modes"><button class="mode" data-mode="attack">⚔️ Attack</button><button class="mode" data-mode="farming">💰 Farming</button><button class="mode active" data-mode="war">🏆 War Screenshot</button><button class="mode" data-mode="base">🏰 Base Design</button></div><h3>3. Screenshot</h3><label for="file" class="upload">📷 Upload base screenshot<br><small>PNG/JPEG/WebP • max 20 MB • auto-compress</small></label><input id="file" type="file" accept="image/png,image/jpeg,image/webp"><div id="previewBox"><img id="preview" alt="Uploaded base"><canvas id="map"></canvas></div><h3>4. Extra details</h3><textarea id="notes" placeholder="Hero levels, equipment, troop levels..."></textarea><button class="go" id="go">⚔️ Analyze + Build Strategy</button><div id="status"></div></div><div class="box" id="result"><h2 id="title"></h2><h3>🔍 Base analysis</h3><div id="read"></div><h3>🧠 Strategy</h3><div id="reason"></div><h3>🪖 Army</h3><div id="army" class="cards"></div><h3>🧪 Spells</h3><div id="spells" class="cards"></div><h3>👑 Heroes & Siege</h3><div id="heroes"></div><h3>🗺️ Screenshot roadmap</h3><div>Green: Entry • Yellow: Funnel • Cyan: Main • Orange: Core • Red: Target • Purple: Spells</div><h3>🚀 Deployment</h3><div id="deployment"></div><h3>⏱️ Timing</h3><div id="timing"></div><h3>🔁 Backup</h3><div id="backup"></div><h3>🎯 Practice</h3><div id="practice"></div><h3>⚠️ Important</h3><div id="warnings" class="warn"></div></div></div><script>
const el=id=>document.getElementById(id);let mode='war',image=null,lastMap=null;
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;});
el('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>20*1024*1024){el('status').textContent='Max 20MB';return;}try{image=await new Promise((ok,bad)=>{const r=new FileReader();r.onerror=bad;r.onload=()=>{const img=new Image();img.onerror=bad;img.onload=()=>{const s=Math.min(1,1600/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.86));};img.src=r.result;};r.readAsDataURL(f);});lastMap=null;el('preview').onload=()=>{el('previewBox').style.display='block';if(lastMap)draw(lastMap);};el('preview').src=image;el('status').textContent='Screenshot ready';}catch{el('status').textContent='Image could not be read';}};
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const steps=a=>(a||[]).map(x=>'<div class="step">'+safe(typeof x==='string'?x:JSON.stringify(x))+'</div>').join('');
function render(p){el('title').textContent=p.title;el('read').textContent=p.baseRead;el('reason').textContent=p.strategyReason;el('army').innerHTML=p.army.map(x=>'<div class="unit"><b>'+safe(x.name)+' × '+safe(x.qty)+'</b><br><small>'+safe(x.role)+'</small></div>').join('');el('spells').innerHTML=(p.spells||[]).map(x=>'<div class="unit"><b>'+safe(x.name)+' × '+safe(x.qty)+'</b><br><small>'+safe(x.role)+'</small></div>').join('');el('heroes').textContent=(p.heroes||[]).join(', ')+' | Siege: '+(p.siege||'None');for(const k of ['deployment','timing','backup','practice','warnings'])el(k).innerHTML=steps(p[k]);lastMap=p.map;el('result').style.display='block';if(image)requestAnimationFrame(()=>draw(lastMap));el('result').scrollIntoView({behavior:'smooth'});}
el('go').onclick=async()=>{if(!el('th').value){alert('Select Town Hall');return;}if(mode==='war'&&!image){alert('Upload war screenshot');return;}el('go').disabled=true;el('status').textContent='Analyzing...';try{const r=await fetch('/api/ask',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({th:el('th').value,mode,message:el('notes').value,image})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');render(d.plan);el('status').textContent='Strategy ready';}catch(e){el('status').textContent='❌ '+e.message;}finally{el('go').disabled=false;}};
function draw(m){if(!m||!image)return;const im=el('preview'),w=im.clientWidth,h=im.clientHeight;if(!w||!h)return;const c=el('map'),r=window.devicePixelRatio||1;c.width=w*r;c.height=h*r;const x=c.getContext('2d');x.setTransform(r,0,0,r,0,0);const pos=p=>[p.x*w/100,p.y*h/100];const arrow=(a,b,color)=>{if(!a||!b)return;const [ax,ay]=pos(a),[bx,by]=pos(b),t=Math.atan2(by-ay,bx-ax);x.strokeStyle=color;x.fillStyle=color;x.lineWidth=3;x.beginPath();x.moveTo(ax,ay);x.lineTo(bx,by);x.stroke();x.beginPath();x.moveTo(bx,by);x.lineTo(bx-12*Math.cos(t-.5),by-12*Math.sin(t-.5));x.lineTo(bx-12*Math.cos(t+.5),by-12*Math.sin(t+.5));x.fill();};const mark=(p,color)=>{if(!p)return;const [a,b]=pos(p);x.fillStyle=color;x.beginPath();x.arc(a,b,6,0,Math.PI*2);x.fill();x.font='bold 11px Arial';const s=String(p.label||'');const tw=x.measureText(s).width;const lx=Math.min(Math.max(2,a+8),Math.max(2,w-tw-12)),ly=Math.min(Math.max(15,b-8),h-5);x.fillStyle='#101722';x.fillRect(lx-2,ly-12,tw+8,16);x.fillStyle='white';x.fillText(s,lx+2,ly);};arrow(m.entry,m.main,'#00ff8c');arrow(m.funnelA,m.main,'#ffcf32');arrow(m.funnelB,m.main,'#ffcf32');arrow(m.main,m.core,'#00e5ff');arrow(m.core,m.target,'#ff5677');mark(m.entry,'#00ff8c');mark(m.funnelA,'#ffcf32');mark(m.funnelB,'#ffcf32');mark(m.main,'#00e5ff');mark(m.core,'#ff9f43');mark(m.target,'#ff5677');(m.spellZones||[]).forEach(p=>mark(p,'#bd80ff'));}window.addEventListener('resize',()=>{if(lastMap)draw(lastMap);});
</script></body></html>`;
